version: "3.9"

services:
  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: melytodo-frontend
    # Frontend dışa açılmıyor; sadece iç ağda 80 dinler
    expose:
      - "80"
    environment:
      # Vite/React benzeri istemci için API tabanı (frontend koduna göre adını düzenleyebilirsin)
      - VITE_API_BASE=https://melygranmomstories.software/api
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: melytodo-backend
    env_file:
      - ./.env
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - appnet

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    # Dışa açmıyoruz; sadece iç ağda
    expose:
      - "27017"
    networks:
      - appnet

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  appnet:
    driver: bridge
