version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src # Geliştirme sırasında kod değişikliklerini yansıtmak için (isteğe bağlı)
      - /app/node_modules # node_modules'in host'tan kopyalanmasını engeller
    environment:
      MONGO_URI: mongodb+srv://Mely:MelyMY1128@melygrandmomstories.qtbqfbz.mongodb.net/MELYtodo?retryWrites=true&w=majority&appName=MelyGrandmomStories
      JWT_SECRET: 6a2684171bcd85bcc76e15eb60439c03f327e4a2dedc41a6d4f7b687b3b015c8
      OPENROUTER_API_KEY: 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
      PORT: 3000
    depends_on:
      - mongo # Backend'in mongo servisine bağımlı olduğunu belirtir
    networks:
      - melytodonetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - melytodonetwork

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Veritabanı verilerini kalıcı hale getir
    networks:
      - melytodonetwork

volumes:
  mongo_data: # mongo_data adında bir volume tanımla

networks:
  melytodonetwork:
    driver: bridge
